import type { ContentBundle, Faq, Insight, Notice, Service, ServiceArea, StaticPage } from "./types";

const seo = (description: string, extra: Partial<Service["seo_ja"]> = {}) => ({
  seo_description: description,
  ...extra,
});

const areas: ServiceArea[] = [
  {
    id: "area-creative",
    slug: "creative",
    anchor: "cr",
    order: 1,
    name_ja: "Creative",
    name_en: "Creative",
    catch_ja: "Design the Experience.",
    catch_en: "Design the Experience.",
    lead_ja: "ビジョンや事業戦略を、体験として形にする。表層のデザインではなく、「なぜそれをつくるのか」から共に考えます。",
    lead_en: "Create possibilities. Shape experiences. We start from why something should exist, not from surface decoration.",
    capabilities_ja: ["要件定義 / 情報設計 / ブランド設計", "Webプロデュース / Webディレクション", "Webデザイン・構築 / UI・UX制作", "映像 / インタラクティブ", "ライティング"],
    capabilities_en: ["Requirements, information architecture, brand", "Web production and direction", "Web design, UI/UX", "Video and interactive", "Writing"],
    seo_ja: seo("クリエイティブ領域では、要件定義からWeb・UI/UX・映像まで、体験として形にします。"),
    seo_en: seo("Creative work spans requirements, web, UI/UX, and video, shaped as an experience."),
    aio_ja: { summary: "クリエイティブ領域は、要件定義、情報設計、Web、UI/UX、映像を、事業の体験としてまとめて扱います。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "The creative area covers requirements, information architecture, web, UI/UX, and video as one experience.", target_audience: "In-house web teams and advertising agencies" },
  },
  {
    id: "area-marketing",
    slug: "marketing",
    anchor: "ma",
    order: 2,
    name_ja: "Marketing",
    name_en: "Marketing",
    catch_ja: "Make it Work. Scale it.",
    catch_en: "Make it Work. Scale it.",
    lead_ja: "構築で終わらせず「使われ・育ち・伸ばす」仕組みを作る。データと仮説で、成長の再現性を高めます。",
    lead_en: "Expand value. Drive results. We build the system that keeps a property in use, and we improve it from data and hypotheses.",
    capabilities_ja: ["分析 / シナリオ仮説 / 実行 / 改善", "インターネット広告運用 / LPO", "SEO / LLMO / AIO / GEO", "戦略設計 / 企画 / ロードマップ策定", "ファネル設計"],
    capabilities_en: ["Analysis, hypotheses, execution, improvement", "Advertising and LPO", "SEO, LLMO, AIO, GEO", "Strategy, planning, roadmaps", "Funnel design"],
    seo_ja: seo("マーケティング領域では、広告、SEO・GEO、分析、ファネル設計を、使われ続ける仕組みとして扱います。"),
    seo_en: seo("Marketing covers advertising, SEO and GEO, analysis, and funnel design as a system that stays in use."),
    aio_ja: { summary: "マーケティング領域は、分析から広告、検索、ファネルまでを、公開後も育つ流れとして設計します。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Marketing connects analysis, advertising, search, and funnels so the work keeps improving after launch.", target_audience: "In-house web teams and advertising agencies" },
  },
  {
    id: "area-ai",
    slug: "ai",
    anchor: "ai",
    order: 3,
    name_ja: "AI & Automation",
    name_en: "AI & Automation",
    catch_ja: "Leverage Intelligence.",
    catch_en: "Leverage Intelligence.",
    lead_ja: "AIは、使う人の創造性と経験を拡張する道具だと考えます。現場で培った判断が、その効果をレバレッジとして機能させます。",
    lead_en: "We treat AI as a way to extend the judgment already in the work, not as a replacement for it.",
    capabilities_ja: ["AIイネーブルメント", "データ収集 / 解析", "ワークフロー自動化 / 効率化", "チェック / デバッグ", "導入サポート"],
    capabilities_en: ["AI enablement", "Data collection and analysis", "Workflow automation", "Review and debugging", "Implementation support"],
    seo_ja: seo("AI・自動化領域では、イネーブルメント、データ、ワークフロー、導入支援を、現場の判断と組み合わせて扱います。"),
    seo_en: seo("AI and automation cover enablement, data, workflows, and implementation support alongside human judgment."),
    aio_ja: { summary: "AIと自動化は、置き換えではなく、現場の判断と経験を拡張する領域として扱います。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "AI and automation extend the judgment already in web and marketing work. They are not a standalone shortcut.", target_audience: "In-house web teams and advertising agencies" },
  },
];

const process = {
  ja: [
    { name: "状況を聞く", description: "課題、体制、いま動いているものを伺います。" },
    { name: "進め方を提案する", description: "範囲と進め方を整理し、個別にお見積りします。" },
    { name: "つくり、直す", description: "設計、制作、運用、改善を、必要な組み合わせで進めます。" },
  ],
  en: [
    { name: "Listen", description: "We start with the situation, the team, and what is already moving." },
    { name: "Propose a way forward", description: "We outline the scope and quote the work individually." },
    { name: "Make and improve", description: "Design, production, operations, and improvement proceed in the combination the work needs." },
  ],
};

const timelineJa = "期間の目安は、内容を伺ったうえでお伝えします。週数は未定のため、この試作には入れていません。内容により変わります。";
const timelineEn = "Timing is shared after we hear the work. Week counts are not published in this prototype. The schedule changes with the scope.";

function service(partial: Omit<Service, "process_ja" | "process_en" | "timeline_note_ja" | "timeline_note_en" | "prototype_copy"> & { prototype_copy?: boolean }): Service {
  return {
    ...partial,
    prototype_copy: partial.prototype_copy ?? true,
    process_ja: process.ja,
    process_en: process.en,
    timeline_note_ja: timelineJa,
    timeline_note_en: timelineEn,
  };
}

const services: Service[] = [
  service({
    id: "svc-web",
    slug: "web-production",
    area: "creative",
    order: 1,
    is_focus: false,
    name_ja: "Webプロデュース・ディレクション",
    name_en: "Web production and direction",
    catch_ja: "なぜつくるのかから、公開まで。",
    catch_en: "From why it exists, through launch.",
    tailwind_benefit_ja: "要件が固まっていない段階から、情報設計と制作を一つの流れにできます。",
    tailwind_benefit_en: "Information architecture and production can move as one flow, including before requirements are fixed.",
    summary_ja: "Webサイトのプロデュース、ディレクション、デザイン、構築を、事業の目的からまとめて進めます。",
    summary_en: "Web production, direction, design, and build, starting from the purpose of the business.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["要件が固まる前に、誰と何を決めるかが曖昧", "デザインと構築が分かれて、意図が落ちる", "公開後の直し先が残っていない"],
    problems_en: ["Decisions are unclear before requirements settle", "Design and build split, and the intent drops", "Nothing is left to improve after launch"],
    solution_ja: "要件定義、情報設計、デザイン、構築を分業で終わらせず、同じ目的に結びます。コーポレート、採用、ブランド、サービスサイトを扱います。",
    solution_en: "Requirements, information architecture, design, and build stay tied to the same purpose. This includes corporate, recruiting, brand, and service sites.",
    deliverables_ja: [
      { name: "情報設計", description: "ページの役割と導線の整理。" },
      { name: "デザインと構築", description: "UIを含むサイトのデザインと実装。" },
    ],
    deliverables_en: [
      { name: "Information architecture", description: "The role of each page and the path between them." },
      { name: "Design and build", description: "Interface design and implementation." },
    ],
    service_type_ja: "Webプロデュース",
    service_type_en: "Web production",
    related_slugs: ["ui-ux", "seo-geo", "photo-sns-video"],
    seo_ja: seo("Webプロデュースとディレクション。要件定義からデザイン、構築までを一つの流れで進めます。", { breadcrumb_label: "Webプロデュース" }),
    seo_en: seo("Web production and direction, from requirements through design and build.", { breadcrumb_label: "Web production" }),
    aio_ja: { summary: "Web制作は、要件、情報設計、デザイン、構築を分業のまま渡さず、一つの流れで進めます。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Web production keeps requirements, architecture, design, and build in one flow.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-ui",
    slug: "ui-ux",
    area: "creative",
    order: 2,
    is_focus: false,
    name_ja: "UI・UX",
    name_en: "UI/UX",
    catch_ja: "体験として、意図が残る形に。",
    catch_en: "An experience that keeps the intent.",
    tailwind_benefit_ja: "画面の見た目の前に、使う人の手順と情報の優先順位を揃えられます。",
    tailwind_benefit_en: "The sequence and the priority of information are settled before the surface is decorated.",
    summary_ja: "UI・UX制作として、情報の順序、画面、操作を、サイトやプロダクトの目的に合わせて設計します。",
    summary_en: "UI/UX design for the order of information, screens, and actions, matched to the purpose of the site or product.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["画面ごとに判断が変わり、操作が揃わない", "必要な情報が、最初の画面に届いていない"],
    problems_en: ["Each screen makes a different decision", "The necessary information never reaches the first screen"],
    solution_ja: "手順と情報の優先順位を先に置き、その上にUIを載せます。",
    solution_en: "We set the sequence and the priority of information first, then design the interface on top.",
    deliverables_ja: [{ name: "画面設計", description: "主要な画面と状態の設計。" }],
    deliverables_en: [{ name: "Screen design", description: "Key screens and their states." }],
    service_type_ja: "UI・UX制作",
    service_type_en: "UI/UX",
    related_slugs: ["web-production", "ai-enablement"],
    seo_ja: seo("UI・UX制作。情報の順序と画面を、サイトやプロダクトの目的に合わせて設計します。", { breadcrumb_label: "UI・UX" }),
    seo_en: seo("UI/UX design for the order of information and the screens that carry it.", { breadcrumb_label: "UI/UX" }),
    aio_ja: { summary: "UI・UXは、画面の装飾の前に、情報の順序と操作を揃える仕事です。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "UI/UX sets the order of information and the actions before decoration.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-photo",
    slug: "photo-sns-video",
    area: "creative",
    order: 3,
    is_focus: true,
    name_ja: "写真・SNS動画",
    name_en: "Photo and SNS video",
    catch_ja: "SNS動画とドローン撮影を軸に。写真は、必要な範囲で。",
    catch_en: "SNS video and drone filming first. Photography where it is needed.",
    tailwind_benefit_ja: "短い動画を、撮影から編集まで一つの相談で進められます。ドローンが要る画も、同じ流れで扱います。",
    tailwind_benefit_en: "Short-form video can move from filming through editing in one conversation. Drone shots sit in the same flow.",
    summary_ja: "SNS動画の撮影・編集とドローン撮影を中心に扱います。写真はそれに続く範囲で対応します。請ける範囲は、問い合わせごとに決めます。",
    summary_en: "The work centers on filming and editing SNS video, and on drone filming. Photography follows where it is needed. Scope is decided per inquiry.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["短い動画を継続して出す手順がない", "上空や広い画が、別の発注になっている", "写真と動画でトーンの相談先が分かれる"],
    problems_en: ["There is no path for ongoing short-form video", "Aerial or wide shots are a separate order", "Photo and video are briefed to different people"],
    solution_ja: "主役は、SNS向け動画の撮影と編集、そしてドローン撮影です。写真は、動画とあわせて必要なときだけ範囲に入れます。できることの一覧で範囲を固定しません。",
    solution_en: "The lead work is SNS video filming and editing, plus drone filming. Photography is included only when the video work needs it. A menu does not fix the scope.",
    deliverables_ja: [
      { name: "SNS動画", description: "撮影と編集。長さや本数は相談で決めます。" },
      { name: "ドローン撮影", description: "上空や広い画が必要なとき。" },
      { name: "写真", description: "動画とあわせて必要な範囲。主役ではありません。" },
    ],
    deliverables_en: [
      { name: "SNS video", description: "Filming and editing. Length and volume are decided in the inquiry." },
      { name: "Drone filming", description: "When the picture needs air or width." },
      { name: "Photography", description: "Only the stills the video work needs. Not the lead offer." },
    ],
    service_type_ja: "SNS動画・ドローン撮影",
    service_type_en: "SNS video and drone filming",
    related_slugs: ["web-production", "advertising"],
    seo_ja: seo("SNS動画の撮影・編集とドローン撮影を中心に、必要な写真も扱います。範囲は相談ごとに決めます。", { breadcrumb_label: "写真・SNS動画" }),
    seo_en: seo("SNS video filming and editing, and drone filming, with photography only where it is needed.", { breadcrumb_label: "Photo and SNS video" }),
    aio_ja: { summary: "写真・SNS動画のページは、SNS動画の撮影・編集とドローン撮影が主役です。写真は従として、相談の範囲で扱います。", target_audience: "企業のWeb担当者と広告代理店", key_points: ["SNS動画の撮影と編集", "ドローン撮影", "写真は必要な範囲のみ"] },
    aio_en: { summary: "This service leads with SNS video filming and editing, and with drone filming. Photography is secondary and scoped per inquiry.", target_audience: "In-house web teams and advertising agencies", key_points: ["SNS video filming and editing", "Drone filming", "Photography only as needed"] },
  }),
  service({
    id: "svc-video",
    slug: "video-interactive",
    area: "creative",
    order: 4,
    is_focus: false,
    name_ja: "映像・インタラクティブ",
    name_en: "Video and interactive",
    catch_ja: "映像と、動く表現。",
    catch_en: "Moving pictures, and interfaces that move.",
    tailwind_benefit_ja: "説明のための映像と、サイト上のインタラクティブな表現を、同じ意図で作れます。",
    tailwind_benefit_en: "Explanatory video and on-site interactive pieces can share one intent.",
    summary_ja: "映像とインタラクティブ表現を、Webやブランドの体験の一部として作ります。",
    summary_en: "Video and interactive work, made as part of a web or brand experience.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["映像だけが別物になり、サイトの意図とずれる", "動きが装飾で終わり、内容が伝わらない"],
    problems_en: ["The film drifts away from the site", "Motion decorates, and the point is lost"],
    solution_ja: "何を伝える映像か、どの操作で何が分かるか、を先に置きます。",
    solution_en: "We start from what the film must say, and what each interaction should make clear.",
    deliverables_ja: [{ name: "映像・インタラクティブ", description: "構成と制作。本数や尺は相談で決めます。" }],
    deliverables_en: [{ name: "Video or interactive", description: "Structure and production. Volume is decided in the inquiry." }],
    service_type_ja: "映像・インタラクティブ",
    service_type_en: "Video and interactive",
    related_slugs: ["photo-sns-video", "web-production"],
    seo_ja: seo("映像とインタラクティブ表現を、Webやブランドの体験の一部として作ります。", { breadcrumb_label: "映像・インタラクティブ" }),
    seo_en: seo("Video and interactive pieces made as part of a web or brand experience.", { breadcrumb_label: "Video and interactive" }),
    aio_ja: { summary: "映像とインタラクティブは、サイトやブランドの意図から外れないように作ります。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Video and interactive work stay attached to the intent of the site or brand.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-ads",
    slug: "advertising",
    area: "marketing",
    order: 5,
    is_focus: false,
    name_ja: "広告運用・LPO",
    name_en: "Advertising and LPO",
    catch_ja: "出して、見て、直す。",
    catch_en: "Run it, read it, revise it.",
    tailwind_benefit_ja: "広告と着地ページを、別々の改善ではなく一つの仮説として直せます。",
    tailwind_benefit_en: "Ads and landing pages can be revised as one hypothesis, not two unrelated fixes.",
    summary_ja: "インターネット広告の運用と、着地ページの改善（LPO）を、仮説と実行の繰り返しとして扱います。",
    summary_en: "Internet advertising and landing-page improvement, treated as a loop of hypothesis and execution.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["配信とページの担当が分かれ、学びが残らない", "何を変えたのかが、次に活きない"],
    problems_en: ["Media and the page are owned apart, so the lesson disappears", "Changes are not carried into the next round"],
    solution_ja: "分析、仮説、実行、改善の順で、広告とLPOを同じテーブルに載せます。",
    solution_en: "Analysis, hypothesis, execution, and improvement keep advertising and LPO on the same table.",
    deliverables_ja: [{ name: "運用と改善", description: "配信と着地ページの改善。媒体の固定メニューはありません。" }],
    deliverables_en: [{ name: "Operations and improvement", description: "Media and landing pages. There is no fixed media menu." }],
    service_type_ja: "広告運用",
    service_type_en: "Advertising operations",
    related_slugs: ["seo-geo", "photo-sns-video", "funnel"],
    seo_ja: seo("インターネット広告の運用とLPOを、分析から改善までの一つの流れで扱います。", { breadcrumb_label: "広告運用" }),
    seo_en: seo("Advertising operations and landing-page improvement in one loop.", { breadcrumb_label: "Advertising" }),
    aio_ja: { summary: "広告運用とLPOは、配信と着地を分けずに、仮説と改善の流れで扱います。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Advertising and LPO stay in one loop of hypothesis and improvement.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-seo",
    slug: "seo-geo",
    area: "marketing",
    order: 6,
    is_focus: false,
    name_ja: "SEO・GEO",
    name_en: "SEO and GEO",
    catch_ja: "検索と、AIの回答に残る形へ。",
    catch_en: "Present in search, and in AI answers.",
    tailwind_benefit_ja: "検索と、AIによる回答・引用の両方を、公開する文章の設計から扱えます。",
    tailwind_benefit_en: "Search and AI answers can be designed into the writing that is published, not added afterwards.",
    summary_ja: "SEO、LLMO、AIO、GEOを、ページの構造と一次情報の示し方から扱います。",
    summary_en: "SEO, LLMO, AIO, and GEO, approached through page structure and how primary sources are shown.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["ページの意味が、初期のHTMLに残っていない", "出典がなく、誰の見解か分からない"],
    problems_en: ["The meaning of the page is not in the initial HTML", "There is no source, so the point of view is unclear"],
    solution_ja: "見出し、要約、出典、構造化データを、公開する本文と一致させます。",
    solution_en: "Headings, summaries, sources, and structured data are kept identical to the published text.",
    deliverables_ja: [{ name: "設計と改善", description: "情報設計、記事、技術的な土台の改善案。" }],
    deliverables_en: [{ name: "Design and improvement", description: "Information architecture, articles, and technical foundations." }],
    service_type_ja: "SEO・GEO",
    service_type_en: "SEO and GEO",
    related_slugs: ["web-production", "strategy"],
    seo_ja: seo("SEO、LLMO、AIO、GEOを、ページ構造と出典の示し方から扱います。", { breadcrumb_label: "SEO・GEO" }),
    seo_en: seo("SEO, LLMO, AIO, and GEO through structure and sources.", { breadcrumb_label: "SEO and GEO" }),
    aio_ja: { summary: "SEOとGEOは、検索結果とAIの回答の両方で、ページの意味が最初から読める状態をつくる仕事です。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "SEO and GEO make the meaning of a page readable from the first HTML, for search and for AI answers.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-strategy",
    slug: "strategy",
    area: "marketing",
    order: 7,
    is_focus: false,
    name_ja: "戦略・ファネル",
    name_en: "Strategy and funnels",
    catch_ja: "何から着手するかを、一緒に置く。",
    catch_en: "Decide what to start, together.",
    tailwind_benefit_ja: "施策の一覧の前に、誰に何をどの順で届けるかを置けます。",
    tailwind_benefit_en: "Before a list of tactics, the audience, the offer, and the order can be set.",
    summary_ja: "戦略設計、企画、ロードマップ、ファネル設計を、実行できる粒度で整理します。",
    summary_en: "Strategy, planning, roadmaps, and funnel design, at a grain that can actually be executed.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["施策が多く、最初の一手が決まらない", "認知から問い合わせまでの道が見えない"],
    problems_en: ["There are many tactics and no first move", "The path from awareness to an inquiry is invisible"],
    solution_ja: "シナリオの仮説を置き、実行と改善に渡せる形にします。",
    solution_en: "We set a scenario hypothesis in a form that execution and improvement can carry.",
    deliverables_ja: [{ name: "方針と導線", description: "ロードマップとファネルの整理。" }],
    deliverables_en: [{ name: "Direction and path", description: "A roadmap and a funnel, written so they can be used." }],
    service_type_ja: "戦略設計",
    service_type_en: "Strategy",
    related_slugs: ["advertising", "seo-geo", "ai-automation"],
    seo_ja: seo("戦略設計、企画、ロードマップ、ファネル設計を、実行できる粒度で整理します。", { breadcrumb_label: "戦略・ファネル" }),
    seo_en: seo("Strategy, planning, roadmaps, and funnel design at a grain that can be executed.", { breadcrumb_label: "Strategy" }),
    aio_ja: { summary: "戦略とファネルは、施策を増やす前に、届ける順序を決める仕事です。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Strategy and funnels decide the order of delivery before adding more tactics.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-enable",
    slug: "ai-enablement",
    area: "ai",
    order: 8,
    is_focus: false,
    name_ja: "AIイネーブルメント",
    name_en: "AI enablement",
    catch_ja: "置き換えではなく、拡張。",
    catch_en: "Extend the work. Don’t replace the judgment.",
    tailwind_benefit_ja: "現場の人がAIを使える状態を、ツールの導入だけで終わらせずに作れます。",
    tailwind_benefit_en: "People on the team can actually use AI, past the moment a tool is switched on.",
    summary_ja: "AIを、思考・制作・運用の精度と速度を高める道具として導入し、使い方が残る状態にします。",
    summary_en: "AI is introduced as a way to raise the precision and speed of thinking, production, and operations, and the way of working remains.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["ツールだけが入って、仕事の手順が変わっていない", "生成物の確認者がいない"],
    problems_en: ["A tool is in place and the work has not changed", "Nobody is responsible for checking what the model produced"],
    solution_ja: "どの工程で使い、どこを人が確認するかを先に決めます。AI単体で完結させる進め方はとりません。",
    solution_en: "We decide where AI is used and where a person checks the result. We do not treat the model as the whole process.",
    deliverables_ja: [{ name: "使い方の設計", description: "対象工程、確認、導入の手順。" }],
    deliverables_en: [{ name: "A way of working", description: "Which steps, which checks, and how it is introduced." }],
    service_type_ja: "AIイネーブルメント",
    service_type_en: "AI enablement",
    related_slugs: ["ai-automation", "web-production"],
    seo_ja: seo("AIイネーブルメント。現場の工程にAIを入れ、人が確認する前提で使い方を残します。", { breadcrumb_label: "AIイネーブルメント" }),
    seo_en: seo("AI enablement that leaves a way of working, with a person checking the result.", { breadcrumb_label: "AI enablement" }),
    aio_ja: { summary: "AIイネーブルメントは、ツール導入ではなく、人が確認する前提で工程にAIを入れる仕事です。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "AI enablement puts AI into a step that a person still checks. It is not a tool install on its own.", target_audience: "In-house web teams and advertising agencies" },
  }),
  service({
    id: "svc-auto",
    slug: "ai-automation",
    area: "ai",
    order: 9,
    is_focus: true,
    name_ja: "AI自動化",
    name_en: "AI automation",
    catch_ja: "繰り返しを、判断が残る形で手放す。",
    catch_en: "Let go of the repeat, and keep the judgment.",
    tailwind_benefit_ja: "手作業の繰り返しを、確認ポイントが残ったワークフローに移せます。",
    tailwind_benefit_en: "Repeated manual steps can move into a workflow that still has a point of review.",
    summary_ja: "ワークフローの自動化と効率化、チェック、導入支援を、AIと人の確認を組み合わせて進めます。",
    summary_en: "Workflow automation, review, and implementation support, combining AI with a human check.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["同じ転記や確認が、人の時間を占有している", "自動化したあとに、誤りに気づく場所がない"],
    problems_en: ["The same copy-and-check work occupies the team", "After automation, there is nowhere to notice an error"],
    solution_ja: "対象の作業を聞き、自動化する範囲と人が見る箇所を分けます。ノーコードで完了、とはしません。デバッグと導入後の確認を含みます。",
    solution_en: "We separate what can be automated from what a person still reviews. A no-code finish line is not the goal. Debugging and a check after introduction are part of the work.",
    deliverables_ja: [
      { name: "ワークフロー", description: "繰り返し作業の自動化。対象は相談で決めます。" },
      { name: "確認の設計", description: "誤りに気づく箇所と、導入後の見方。" },
    ],
    deliverables_en: [
      { name: "A workflow", description: "Automation of repeated work. The target is decided in the inquiry." },
      { name: "A review point", description: "Where an error is noticed, and how to look after launch." },
    ],
    service_type_ja: "業務自動化",
    service_type_en: "Workflow automation",
    related_slugs: ["ai-enablement", "data-analysis", "strategy"],
    seo_ja: seo("AIを使ったワークフロー自動化。確認する箇所を残し、導入とデバッグまで扱います。", { breadcrumb_label: "AI自動化" }),
    seo_en: seo("AI workflow automation that keeps a human review, through implementation and debugging.", { breadcrumb_label: "AI automation" }),
    aio_ja: { summary: "AI自動化は、繰り返し作業をワークフローに移し、人が確認する箇所を残すサービスです。範囲は相談ごとに決めます。", target_audience: "企業のWeb担当者と広告代理店", key_points: ["ワークフロー自動化", "チェックとデバッグ", "導入サポート"] },
    aio_en: { summary: "AI automation moves repeated work into a workflow and keeps a human review. Scope is decided per inquiry.", target_audience: "In-house web teams and advertising agencies", key_points: ["Workflow automation", "Review and debugging", "Implementation support"] },
  }),
  service({
    id: "svc-data",
    slug: "data-analysis",
    area: "ai",
    order: 10,
    is_focus: false,
    name_ja: "データ収集・解析",
    name_en: "Data collection and analysis",
    catch_ja: "集めて終わりにしない。",
    catch_en: "Collection is not the end.",
    tailwind_benefit_ja: "散らばった数字を、次の制作や運用の判断に渡せる形にできます。",
    tailwind_benefit_en: "Scattered numbers can be handed to the next production or operations decision.",
    summary_ja: "データの収集と解析を、改善の仮説につなげます。",
    summary_en: "Data collection and analysis, connected to a hypothesis for improvement.",
    audience_ja: ["企業のWeb担当者", "広告代理店"],
    audience_en: ["In-house web teams", "Advertising agencies"],
    problems_ja: ["数字はあるが、次に何を変えるかが決まらない", "計測と制作が別の会話になっている"],
    problems_en: ["The numbers exist and the next change does not", "Measurement and production are separate conversations"],
    solution_ja: "見る指標と、そのあと変えるものをセットで置きます。",
    solution_en: "The metric and the thing that will change are set together.",
    deliverables_ja: [{ name: "見方と仮説", description: "収集の範囲と、改善の仮説。" }],
    deliverables_en: [{ name: "A reading and a hypothesis", description: "What is collected, and what might change." }],
    service_type_ja: "データ解析",
    service_type_en: "Data analysis",
    related_slugs: ["ai-automation", "advertising", "seo-geo"],
    seo_ja: seo("データの収集と解析を、次の制作や運用の判断につなげます。", { breadcrumb_label: "データ解析" }),
    seo_en: seo("Data collection and analysis connected to the next production or operations decision.", { breadcrumb_label: "Data" }),
    aio_ja: { summary: "データ収集と解析は、数字を揃えることではなく、次に変えるものを決めるために行います。", target_audience: "企業のWeb担当者と広告代理店" },
    aio_en: { summary: "Data work exists to decide the next change, not only to collect numbers.", target_audience: "In-house web teams and advertising agencies" },
  }),
];

const faqs: Faq[] = [
  {
    id: "faq-1",
    scope: ["general"],
    services: [],
    order: 1,
    question_ja: "他社との違いは何ですか？",
    question_en: "How is this different from other studios?",
    answer_ja: "クリエイティブ、マーケティング、テクノロジーを、本来は一体のものとして捉えています。一方で、プロジェクトのフェーズや体制に合わせて、特定の領域からの相談にも対応します。部分から始め、必要に応じて全体へ広げられます。",
    answer_en: "Creative, marketing, and technology are treated as one body of work. A project can still start from a single area and widen only if it needs to.",
  },
  {
    id: "faq-2",
    scope: ["general", "service"],
    services: ["ai-enablement", "ai-automation"],
    order: 2,
    question_ja: "AIはどのように活用していますか？",
    question_en: "How do you use AI?",
    answer_ja: "AIを「置き換え」ではなく「拡張」として使います。専門の判断を持つ人がAIを使い、思考、制作、運用の精度と速度を高めます。ノーコードツールで完了とするような、AI単体で完結する進め方はとりません。新しい情報は検証してから仕事に入れます。",
    answer_en: "AI extends the work. It does not replace judgment. A person with the relevant craft uses it to raise the precision and speed of thinking, production, and operations. We do not finish at a no-code tool.",
  },
  {
    id: "faq-3",
    scope: ["general"],
    services: [],
    order: 3,
    question_ja: "プロジェクトの上流工程から任せられますか？",
    question_en: "Can you start from the upstream of a project?",
    answer_ja: "はい、対応できます。Web制作・マーケティングの現場で、20年以上にわたり実務を積み重ねてきました。まずはお話を伺い、対応できる範囲かを確認します。",
    answer_en: "Yes. The work is grounded in more than 20 years of practice in web production and marketing. We start by listening, then confirm the scope we can take.",
  },
  {
    id: "faq-4",
    scope: ["general"],
    services: [],
    order: 4,
    question_ja: "小規模なプロジェクトやスポット対応も可能ですか？",
    question_en: "Do you take small or one-off projects?",
    answer_ja: "はい、可能です。単発のWeb制作、広告運用、AIツールの導入など、規模にかかわらず相談を受けます。内容に応じて進め方を提案します。",
    answer_en: "Yes. One-off web production, advertising operations, and AI tool introduction are all open for discussion. The way of working follows the content.",
  },
  {
    id: "faq-5",
    scope: ["general"],
    services: [],
    order: 5,
    question_ja: "遠方からの依頼も可能ですか？",
    question_en: "Can you work with teams outside Tokyo and Fukuoka?",
    answer_ja: "はい、可能です。ビデオミーティングでやり取りできれば、場所は問いません。まずは一度ご相談ください。",
    answer_en: "Yes. If we can work by video meeting, location is not a condition. Start with a conversation.",
  },
  {
    id: "faq-6",
    scope: ["general"],
    services: [],
    order: 6,
    question_ja: "契約前に相談や見積もりはできますか？",
    question_en: "Can we talk and get an estimate before a contract?",
    answer_ja: "はい、ご相談は無料です。ヒアリングのあと、進め方と概算のお見積りを提案します。料金の定価表はありません。",
    answer_en: "Yes. The initial conversation is free. After the hearing we propose a way forward and a rough estimate. There is no price list.",
  },
  {
    id: "faq-7",
    scope: ["general"],
    services: [],
    order: 7,
    question_ja: "どのフェーズから相談できますか？",
    question_en: "Which phase can we start from?",
    answer_ja: "どの段階からでも相談できます。構想段階、企画の前、既存施策の改善など、フェーズを問いません。進行中のプロジェクトについての相談も受けます。",
    answer_en: "Any phase. Early ideas, pre-planning, or improvement of something already running. Ongoing projects are welcome too.",
  },
  {
    id: "faq-8",
    scope: ["general"],
    services: [],
    order: 8,
    question_ja: "依頼時に必要なものはありますか？",
    question_en: "What do we need to prepare?",
    answer_ja: "特別な準備は不要です。まずは打ち合わせで伺い、要件、お見積り、スケジュールを提案します。初めての取引では、NDAや業務委託契約を結びます。ご希望があれば、詳細を伺う前にNDAを先に結べます。",
    answer_en: "Nothing special. We listen first, then propose requirements, an estimate, and a schedule. A first engagement uses an NDA and a service contract. The NDA can come before the detailed hearing if you prefer.",
  },
];

const notices: Notice[] = [
  {
    id: "notice-01",
    slug: "01",
    date: "2025-10-06",
    title_ja: "NeoLeverage株式会社を創業 — デジタルとAIで企業価値を最大化",
    title_en: "NeoLeverage Founded — Maximizing Business Value with Digital & AI",
    body_ja: [
      "NeoLeverage株式会社は、2025年10月6日に創業いたしました。",
      "私たちは、Web制作、デジタルマーケティング、AIを活用したクリエイティブ領域を中心に、企業のデジタル成長を支援するパートナーとして事業を展開してまいります。",
      "テクノロジーの進化によって、企業の情報発信や顧客接点のあり方は大きく変化しています。NeoLeverageは、戦略・クリエイティブ・テクノロジーを横断的に組み合わせることで、企業の価値を最大化するデジタルソリューションを提供します。",
      "これからも柔軟な発想とスピードを大切にしながら、クライアントと共に新しい価値を創出してまいります。",
    ],
    body_en: [
      "NeoLeverage was founded on October 6, 2025.",
      "We operate as a partner supporting companies’ digital growth, focusing on web production, digital marketing, and AI-driven creative.",
      "As technology evolves, the way companies communicate and connect with customers is rapidly changing. By integrating strategy, creative, and technology, NeoLeverage delivers digital solutions that maximize business value.",
      "We will continue to move forward with flexibility and speed, creating new value together with our clients.",
    ],
    seo_ja: seo("NeoLeverage株式会社は、2025年10月6日に創業しました。Web制作、デジタルマーケティング、AIを活用したクリエイティブを中心に事業を展開します。"),
    seo_en: seo("NeoLeverage was founded on October 6, 2025, focused on web production, digital marketing, and AI-driven creative."),
  },
  {
    id: "notice-02",
    slug: "02",
    date: "2025-10-06",
    title_ja: "Web制作・デジタルマーケティング支援事業を開始しました",
    body_ja: [
      "NeoLeverage株式会社では、Web制作およびデジタルマーケティング支援事業を開始いたしました。",
      "企業のWebサイト制作、広告運用支援、デジタル施策の企画・実行などを通じて、企業の成長を支援するサービスを提供してまいります。",
      "今後もクライアントの事業成長に貢献できるデジタル支援を行ってまいります。",
    ],
    seo_ja: seo("Web制作およびデジタルマーケティング支援事業を開始しました。サイト制作、広告運用、デジタル施策の企画と実行を扱います。"),
  },
  {
    id: "notice-03",
    slug: "03",
    date: "2025-10-06",
    title_ja: "生成AIを活用した制作ワークフローを構築",
    body_ja: [
      "NeoLeverage株式会社では、生成AIを活用した制作ワークフローの構築を進めております。",
      "近年、生成AIの進化により、コンテンツ制作やクリエイティブ制作のプロセスは大きく変化しています。当社では、AI技術を制作工程に取り入れることで、制作体制の効率化と高品質化の実現を目指しています。",
      "また、AIによる自動化と人のクリエイティブな発想を組み合わせることで、これまでにない新しい表現や制作手法の可能性を探求してまいります。",
      "今後も最新のテクノロジーを積極的に取り入れながら、企業のデジタル活用とクリエイティブ制作を支援してまいります。",
    ],
    seo_ja: seo("生成AIを制作工程に取り入れ、人と組み合わせた制作ワークフローの構築を進めています。"),
  },
  {
    id: "notice-05",
    slug: "05",
    date: "2025-10-06",
    title_ja: "制作パートナー募集のお知らせ",
    body_ja: [
      "NeoLeverage株式会社では、Web制作やクリエイティブ制作にご協力いただけるパートナー企業・フリーランスの皆さまを募集しております。",
      "Webデザイン、コーディング、動画制作、マーケティング支援など、さまざまな分野での協力体制を構築していきたいと考えております。",
      "ご興味のある方は、お問い合わせフォームよりご連絡ください。",
    ],
    seo_ja: seo("Web制作やクリエイティブ制作のパートナー企業・フリーランスを募集しています。連絡はお問い合わせフォームから。"),
  },
  {
    id: "notice-07",
    slug: "07",
    date: "2025-10-06",
    title_ja: "業務委託クリエイター募集のお知らせ",
    body_ja: [
      "NeoLeverage株式会社では、プロジェクトベースでご協力いただける業務委託クリエイターを募集しております。",
      "Webデザイン、UI/UXデザイン、動画制作、マーケティング支援など、幅広い分野のクリエイターの皆さまと協力しながらプロジェクトを進めてまいります。",
      "ご興味のある方は、お気軽にお問い合わせください。",
    ],
    seo_ja: seo("プロジェクト単位で協力いただける業務委託クリエイターを募集しています。"),
  },
  {
    id: "notice-08",
    slug: "08",
    date: "2026-01-05",
    title_ja: "企業のデジタル活用を支援するプロジェクトを開始",
    title_en: "Launching a Project to Support Digital Growth",
    body_ja: [
      "NeoLeverage株式会社では、企業のデジタル活用を支援するプロジェクトを開始いたしました。",
      "Webサイト制作やデジタルマーケティング、AI活用などの分野において、企業の課題に合わせた支援を行ってまいります。",
      "今後も企業の成長を支えるパートナーとして、価値あるサービスの提供を目指してまいります。",
    ],
    body_en: [
      "NeoLeverage has launched a new project to support companies in leveraging digital.",
      "We provide tailored support across web production, digital marketing, and AI, aligned with each company’s challenges.",
      "We aim to be a trusted partner, delivering value that drives business growth.",
    ],
    seo_ja: seo("企業のデジタル活用を支援するプロジェクトを開始しました。Web制作、デジタルマーケティング、AI活用を扱います。"),
    seo_en: seo("A project to support companies in leveraging digital has started, across web, marketing, and AI."),
  },
  {
    id: "notice-11",
    slug: "11",
    date: "2026-03-08",
    title_ja: "NeoLeverage株式会社の事業内容を公開しました",
    title_en: "NeoLeverage Services Now Available",
    body_ja: [
      "このたび、NeoLeverage株式会社の事業内容ページを公開いたしました。",
      "当社では、Web制作、デジタルマーケティング、AIを活用したクリエイティブ制作など、企業のデジタル活用を支援するサービスを提供しております。",
      "今後もサービスの拡充を図りながら、企業の成長を支援してまいります。",
    ],
    body_en: [
      "We have published the services page for NeoLeverage.",
      "We provide services that support companies’ digital growth, including web production, digital marketing, and AI-driven creative.",
      "We will continue to expand our offerings and support business growth.",
    ],
    seo_ja: seo("事業内容ページを公開しました。Web制作、デジタルマーケティング、AIを活用したクリエイティブを掲載しています。"),
    seo_en: seo("The services page is published, covering web production, digital marketing, and AI-driven creative."),
  },
  {
    id: "notice-09",
    slug: "09",
    date: "2026-03-08",
    title_ja: "Web・AI・マーケティングに関する情報発信を開始",
    title_en: "Launching insights on Web, AI, and Marketing",
    body_ja: [
      "NeoLeverage株式会社では、Web制作、AI、デジタルマーケティングに関する情報発信を開始いたしました。",
      "当サイトを通じて、デジタル分野の最新トレンドや実践的な知見を継続的に発信してまいります。",
      "企業のデジタル活用に役立つコンテンツの提供を目指してまいります。",
    ],
    body_en: [
      "NeoLeverage has begun sharing insights on web production, AI, and digital marketing.",
      "Through this site, we will continuously provide the latest trends and practical knowledge in the digital space.",
      "Our goal is to deliver content that supports companies in leveraging digital effectively.",
    ],
    seo_ja: seo("Web制作、AI、デジタルマーケティングに関する情報発信を開始しました。"),
    seo_en: seo("Insights on web production, AI, and digital marketing have started on this site."),
  },
  {
    id: "notice-10",
    slug: "10",
    date: "2026-03-17",
    title_ja: "コーポレートサイトを公開しました",
    title_en: "Our corporate website is now live.",
    body_ja: [
      "このたび、NeoLeverage株式会社のコーポレートサイトを公開いたしました。",
      "本サイトでは、当社の事業内容やサービス、取り組みなどの情報を発信してまいります。",
      "今後もコンテンツの充実を図りながら、有益な情報をお届けしてまいります。",
    ],
    body_en: [
      "We’re pleased to announce the launch of NeoLeverage’s corporate website.",
      "Through this site, we will share information about our business, services, and initiatives.",
      "We will continue to expand our content and provide valuable insights.",
    ],
    seo_ja: seo("NeoLeverage株式会社のコーポレートサイトを公開しました。"),
    seo_en: seo("NeoLeverage’s corporate website is now live."),
  },
  {
    id: "notice-12",
    slug: "12",
    date: "2026-03-27",
    title_ja: "外語ページ（EN）をリリースしました。",
    title_en: "The English version (EN) has been released.",
    body_ja: [
      "平素より当サイトをご覧いただき、誠にありがとうございます。",
      "このたび、英語版（EN）ページを公開いたしました。",
      "グローバルに情報発信を強化し、さらなる価値提供に努めてまいります。",
    ],
    body_en: [
      "Thank you for visiting our website.",
      "We are pleased to announce that the English (EN) version of our site has been launched.",
      "We will continue to strengthen our global communication and deliver even greater value.",
    ],
    seo_ja: seo("英語版（EN）ページを公開しました。"),
    seo_en: seo("The English version of the site has been released."),
  },
];

const insights: Insight[] = [
  {
    id: "ins-1",
    slug: "2026092822462803",
    published_at: "2026-09-28",
    category: "tech",
    tags: ["wordpress"],
    title_ja: "WP Engine対Automattic訴訟、独占禁止法の主張が裁判で生き残る",
    title_en: "WP Engine's Antitrust Claims Against Automattic Survive Dismissal Motion",
    lead_ja: "WP EngineとAutomattic間の独占禁止法訴訟で、裁判所がWP Engineの主要な主張を認める一方、被告側の反訴も存続させる複雑な判断を下しました。今後、両者の主張が本格的に審理される見通しです。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("WP EngineとAutomattic間の独占禁止法訴訟で、裁判所がWP Engineの主要な主張を認める一方、被告側の反訴も存続させる判断を下した、という現行サイトの要約です。"),
    seo_en: seo("English body pending migration. The Japanese page carries the summary published on the current site.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトに掲載されている要約を再掲しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-2",
    slug: "2026092822462804",
    published_at: "2026-09-28",
    category: "marketing",
    tags: ["seo"],
    title_ja: "Google検索のトラフィック減少が加速、画像検索データも解禁に",
    title_en: "Google Search Traffic Decline Accelerates as Image Search Data Becomes Available",
    lead_ja: "Googleのスパムアップデート展開期間が2週間に延長され、Search Consoleに画像検索フィルタが追加された。パブリッシャーの検索流入は40%減少し、AI Mode強制利用でクリック率が約19ポイント低下した実験結果も報告されている。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("Search Consoleの画像検索フィルタと、検索流入の変化について、現行サイトに掲載されている要約です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの要約を再掲しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-3",
    slug: "2026092822462807",
    published_at: "2026-09-28",
    category: "ai",
    tags: ["ai"],
    title_ja: "GoogleがAI生成スパムを検出する新システム「SAFE」を実戦投入",
    title_en: "Google Deploys SAFE: A New AI-Powered Spam Detection System",
    lead_ja: "GoogleがAI生成スパムを検出する新システム「SAFE」を実戦投入しました。このシステムは4つの専門AIエージェントを活用し、従来の分類器では捕捉できなかったポリシー違反を検出します。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("Googleのスパム検出システムSAFEについて、現行サイトに掲載されている要約です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの要約を再掲しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-4",
    slug: "2026092822462809",
    published_at: "2026-09-28",
    category: "creative",
    tags: ["web"],
    title_ja: "不動産サイト制作で失敗しない、デザイン会社選びの5つのチェックポイント",
    title_en: "5 Critical Checkpoints for Choosing the Right Real Estate Web Design Agency",
    lead_ja: "不動産Webサイト制作におけるデザイン会社選定では、ポートフォリオの見栄えだけでなく、複数物件・複数カテゴリーを統合できることと、既存ブランドを進化させる力が重要である、と現行サイトは解説しています。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("不動産サイト制作のデザイン会社選びに関する、現行サイトの記事タイトルと要約です。本文は移行前です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの標題を維持しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-5",
    slug: "2026091020321415",
    published_at: "2026-09-10",
    category: "ai",
    tags: ["ai", "seo"],
    title_ja: "AI可視性スコアは本当に有益か?測定と実務のギャップを検証",
    title_en: "Are AI Visibility Scores Actually Useful? Examining the Gap Between Metrics and Action",
    lead_ja: "AI可視性スコアは「メンション」と「サイテーション」を組み合わせた指標だが、スコアの変動が何を意味するかは必ずしも明確ではない、と現行サイトはまとめています。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("AI可視性スコアの測定と実務のギャップについて、現行サイトに掲載されている要約です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの要約を再掲しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-6",
    slug: "2026091020321412",
    published_at: "2026-09-10",
    category: "ai",
    tags: ["ai", "seo"],
    title_ja: "検索の未来が変わる：AIが塗り替える情報探索の新しい形",
    title_en: "How AI Is Fundamentally Reshaping Search Intent and User Behavior",
    lead_ja: "検索行動の変化と、AI Overviewへの最適化について、現行サイトが掲載している記事です。本文は移行前のため、この試作では要約のみを再掲します。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("AIが検索行動を変えるというテーマの、現行サイトの記事です。本文は移行前です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの標題を維持しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-7",
    slug: "2026082815480116",
    published_at: "2026-08-28",
    category: "creative",
    tags: ["web"],
    title_ja: "FigmaがCSSと同じ言葉で話し始めた。AIコーディング時代の新常識",
    title_en: "Figma Now Speaks CSS: The New Standard for AI-Powered Coding",
    lead_ja: "FigmaのAuto LayoutとCSS Flexboxの対応について、現行サイトに掲載されている記事です。本文は移行前です。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("FigmaのAuto LayoutとCSSの対応について、現行サイトに掲載されている記事です。本文は移行前です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの標題を維持しています。本文と出典は移行前です。" },
  },
  {
    id: "ins-8",
    slug: "202604092002a",
    published_at: "2026-04-09",
    category: "ai",
    tags: ["ai"],
    title_ja: "GensparkのAI Workspace 4.0、デスクトップとOfficeを統合する新機能を発表",
    title_en: "Genspark Unveils AI Workspace 4.0 with Desktop and Office Integration",
    lead_ja: "GensparkのAI Workspace 4.0について、現行サイトに掲載されている記事です。本文は移行前です。",
    eyecatch_alt_ja: "水平線のプレースホルダー画像。記事の図版は移行前です。",
    eyecatch_alt_en: "Placeholder horizon. The article figure has not been migrated.",
    body_pending: true,
    seo_ja: seo("GensparkのAI Workspace 4.0について、現行サイトに掲載されている記事です。本文は移行前です。"),
    seo_en: seo("English body pending migration.", { noindex: true, exclude_from_sitemap: true }),
    aio_ja: { summary: "現行サイトの標題を維持しています。本文と出典は移行前です。" },
  },
];

const pages: StaticPage[] = [
  {
    id: "page-privacy",
    slug: "privacy",
    title_ja: "プライバシーポリシー",
    title_en: "Privacy Policy",
    revised_note_ja: "現行サイトに制定日・改定日の記載は見当たりません。この試作では日付を創作していません。",
    revised_note_en: "The current site does not show an enacted or revised date. This prototype does not invent one.",
    sections_ja: [
      { heading: "はじめに", paragraphs: ["NeoLeverage株式会社（以下「当社」といいます）は、当社が提供するWebサイトおよび各種サービス（以下「本サービス」といいます）において取得する個人情報について、以下のとおりプライバシーポリシーを定め、適切な保護と管理に努めます。"] },
      { heading: "個人情報の取得について", paragraphs: ["当社は、適法かつ公正な手段により、以下の場合に個人情報を取得することがあります。", "お問い合わせフォームの送信時。サービスのご相談・ご依頼時。資料請求、メールマガジン登録時。採用活動への応募時。その他、当社サービスの利用に関連して必要となる場合。", "取得する情報には、氏名、会社名、メールアドレス、電話番号、その他入力フォームに記載された情報が含まれます。"] },
      { heading: "個人情報の利用目的", paragraphs: ["お問い合わせ・ご相談への回答。サービスの提供、業務上のご連絡。お見積り・ご提案・契約手続き。サービス改善・品質向上のための分析。採用活動に関する選考および連絡。法令または利用規約に基づく対応。"] },
      { heading: "個人情報の管理", paragraphs: ["当社は、個人情報の漏えい、滅失、毀損、不正アクセス等を防止するため、合理的かつ適切な安全管理措置を講じます。"] },
      { heading: "個人情報の第三者提供", paragraphs: ["当社は、法令に基づく場合、人の生命、身体または財産の保護のために必要な場合、業務遂行上必要な範囲で業務委託先に提供する場合を除き、本人の同意なく個人情報を第三者に提供することはありません。委託先には適切な監督を行います。"] },
      { heading: "個人情報の開示・訂正・削除", paragraphs: ["本人から、自己の個人情報について開示・訂正・追加・削除・利用停止等の請求があった場合、法令に従い適切に対応します。", "代表者の氏名はサイトには掲載していません。ご本人からお求めがあった場合には、遅滞なくお知らせします。"] },
      { heading: "Cookie（クッキー）等の利用について", paragraphs: ["当社Webサイトでは、利便性向上や利用状況の把握のため、Cookie等の技術を利用する場合があります。Cookieにより取得される情報には、それ単独で個人を特定する情報は含まれません。"] },
      { heading: "外部送信について", paragraphs: ["アクセス解析のため、Google タグ マネージャーを読み込むことがあります。このタグは、簡易的なデータ管理（DMP）を含む、計測用の外部サービスを追加で読み込むことがあります。送信されるのは、閲覧に伴う識別子や閲覧状況など、各サービスの仕様に従った情報です。タグの有無は、サイトの設定で切り替えます。"] },
      { heading: "プライバシーポリシーの変更", paragraphs: ["本ポリシーの内容は、法令の改正やサービス内容の変更等に応じて改定されることがあります。最新の内容は本ページにて公開します。"] },
      { heading: "お問い合わせ窓口", paragraphs: ["個人情報の取扱いに関するお問い合わせは、お問い合わせフォームからご連絡ください。"] },
    ],
    sections_en: [
      { heading: "Introduction", paragraphs: ["NeoLeverage Inc. (“we”) sets this privacy policy for personal information obtained through our website and services, and we work to protect and manage it appropriately."] },
      { heading: "When we collect information", paragraphs: ["We may collect personal information when you send the contact form, discuss or request a service, request materials or a newsletter, apply for recruiting, or when it is otherwise needed to use a service.", "This can include a name, company, email address, phone number, and other information entered in a form."] },
      { heading: "How we use it", paragraphs: ["To answer inquiries, provide services, prepare estimates and contracts, improve the service, handle recruiting, and meet legal duties."] },
      { heading: "How we keep it", paragraphs: ["We take reasonable measures against leakage, loss, damage, and unauthorized access."] },
      { heading: "Sharing", paragraphs: ["We do not share personal information with third parties without consent, except where the law requires it, where it is needed to protect life, body, or property, or where a contractor needs it to do the work under our supervision."] },
      { heading: "Requests", paragraphs: ["We respond to requests for disclosure, correction, addition, deletion, or suspension as the law requires.", "The representative’s name is not published on the site. It is provided without delay when requested."] },
      { heading: "Cookies", paragraphs: ["The site may use cookies to understand how it is used. A cookie on its own does not identify a person."] },
      { heading: "External transmission", paragraphs: ["For measurement, the site may load Google Tag Manager. That tag can load further measurement services, including a simple data-management platform. What is sent follows each service. The tag is controlled by site configuration."] },
      { heading: "Changes", paragraphs: ["This policy may be revised. The current text is published on this page."] },
      { heading: "Contact", paragraphs: ["Questions about personal information go through the contact form."] },
    ],
    seo_ja: seo("NeoLeverage株式会社のプライバシーポリシー。取得、利用目的、外部送信、開示の請求について定めます。", { breadcrumb_label: "プライバシーポリシー" }),
    seo_en: seo("Privacy policy of NeoLeverage Inc., covering collection, use, external tags, and requests.", { breadcrumb_label: "Privacy Policy" }),
  },
  {
    id: "page-editorial",
    slug: "editorial-policy",
    title_ja: "編集方針",
    title_en: "Editorial Policy",
    revised_note_ja: "このページは新設の試作です。現行サイトには同じページがありません。",
    revised_note_en: "This page is new prototype copy. The current site does not have the same page.",
    sections_ja: [
      { heading: "Trends の目的", paragraphs: ["Trends は、AI、クリエイティブ、マーケティング、テックの動きを、企業のWeb担当者と広告代理店が仕事に使える粒度で読むためのメディアです。"] },
      { heading: "記事の作り方", paragraphs: ["ニュースの要約だけで終えず、一次情報へのリンクと、NeoLeverageとしての視点を添える方針です。視点は個人の署名ではなく、NeoLeverage編集部の見解として書きます。"] },
      { heading: "出典", paragraphs: ["新規と改稿の記事には、公式発表、論文、判決、公式ブログなどの一次情報を少なくとも一つ示します。この試作に載っている記事は移行前のため、出典欄はまだ空です。"] },
      { heading: "AI の利用", paragraphs: ["AIは下書きや翻訳の補助に使うことがあります。公開前に、人が事実と出典を確認します。記事ごとの利用の有無は、このページで方針として示し、記事の署名にはしません。"] },
      { heading: "訂正", paragraphs: ["誤りに気づいた場合は、記事を修正し、必要なときはその旨を記事内に残します。連絡はお問い合わせフォームから受けます。"] },
      { heading: "広告・PR", paragraphs: ["広告や提供を伴う記事を出す場合は、その旨を記事上で分かるようにします。この試作の記事は、その表示が必要な契約を確認する前の再掲です。"] },
    ],
    sections_en: [
      { heading: "What Trends is for", paragraphs: ["Trends reads AI, creative, marketing, and technology for in-house web teams and advertising agencies, at a grain they can use."] },
      { heading: "How articles are made", paragraphs: ["A summary is not enough. New and revised articles add a primary source and a NeoLeverage perspective. The perspective is written as the NeoLeverage Editorial Team, not as a named person."] },
      { heading: "Sources", paragraphs: ["New and revised articles cite at least one primary source. Articles in this prototype are not migrated yet, so the source list is still empty."] },
      { heading: "Use of AI", paragraphs: ["AI may assist a draft or a translation. A person checks facts and sources before publication. That practice is stated here, not as a byline."] },
      { heading: "Corrections", paragraphs: ["When we find an error we correct the article and, when needed, say so on the page. Write to us through the contact form."] },
      { heading: "Advertising", paragraphs: ["If an article is sponsored, the page will say so. The sample articles here are republished titles, before that check."] },
    ],
    seo_ja: seo("NeoLeverage編集部の編集方針。記事の作り方、出典、AIの利用、訂正について。", { breadcrumb_label: "編集方針" }),
    seo_en: seo("Editorial policy of the NeoLeverage Editorial Team: sources, AI assistance, and corrections.", { breadcrumb_label: "Editorial Policy" }),
  },
];

export const mockBundle: ContentBundle = {
  source: "mock",
  settings: {
    legal_name_ja: "NeoLeverage株式会社",
    legal_name_en: "NeoLeverage Inc.",
    name_kana: "ネオレバレッジ",
    alternate_names: [],
    site_name: "NeoLeverage",
    site_alternate_names: ["NeoLeverage株式会社", "ネオレバレッジ"],
    founding_date: "2025-10-06",
    editorial_name_ja: "NeoLeverage編集部",
    editorial_name_en: "NeoLeverage Editorial Team",
    editorial_description_ja: "日々の研究内容や、業界の旬な情報をピックアップしてお届けします。",
    editorial_description_en: "Research and current notes from the industry, published by the team.",
    tagline_ja: "順風満帆。帆を張れ、追い風だ。",
    tagline_en: "Tailwinds For Your Growth",
    description_ja: "デジタル領域の企画・制作・マーケティングを支援するクリエイティブチーム。Webコンサルティング、Web開発、AI開発を通じて、企業のブランド価値とビジネスの成長を支援します。",
    description_en: "A creative team supporting planning, production, and marketing in the digital space. Through web consulting, web development, and AI development, we help enhance brand value and drive business growth.",
    knows_about_ja: ["クリエイティブ（Web制作・UI/UX・映像）", "Webマーケティング（広告運用・SEO・GEO）", "AI活用・業務自動化"],
    knows_about_en: ["Creative (web production, UI/UX, video)", "Web marketing (advertising, SEO, GEO)", "AI enablement and workflow automation"],
    area_served: ["東京都", "日本"],
    quote_policy_ja: "料金は内容に応じて個別にお見積りします。定価表やパッケージ販売はありません。",
    quote_policy_en: "Fees are quoted individually. There is no price list and no packaged offer.",
    corporate_number: "1290001111832",
    same_as: [],
    business_summary_ja: [
      "Webプロデュース",
      "Webディレクション",
      "UI・UX設計",
      "Web・映像・3D・アニメーション制作",
      "AI × Creative",
      "Eコマース",
      "システムインテグレーション",
      "ワークフロー・自動化・効率化",
      "Webマーケティング",
      "リスティング・SNS広告運用",
      "SEO・GEO",
      "データ解析・改善",
      "LPO・CRO戦略",
      "導入支援・プロダクト開発",
      "メディアプランニング",
      "メディア運営",
    ],
    business_summary_en: [
      "Web Production",
      "Web Direction",
      "UI/UX Design",
      "Web, Video, 3D & Animation Production",
      "AI × Creative",
      "E-commerce",
      "System Integration",
      "Workflow Automation & Optimization",
      "Web Marketing",
      "Listing & Social Ads",
      "SEO / GEO",
      "Data Analysis & Optimization",
      "LPO / CRO Strategy",
      "Implementation Support / Product Development",
      "Media Planning",
      "Media Operations",
    ],
    llms_intro_ja: "NeoLeverage株式会社（ネオレバレッジ）は、企画から制作・運用までを扱うデジタルクリエイティブカンパニーです。クリエイティブ、マーケティング、AIを分けずに扱います。連絡は問い合わせフォームのみです。",
    llms_intro_en: "NeoLeverage Inc. is a digital creative company covering planning, production, and operations. Creative, marketing, and AI are handled together. Contact is through the form only.",
    ai_crawler_policy: "allow",
    offices: [
      {
        id: "fukuoka",
        name: "福岡",
        name_en: "Fukuoka",
        postal_code: "810-0001",
        address_region: "福岡県",
        address_locality: "福岡市中央区",
        street_address: "天神2丁目2番12号 T&Jビルディング7F",
        address_en: "7F, T&J Building, 2-2-12 Tenjin, Chuo-ku, Fukuoka 810-0001, Japan",
        is_headquarters: true,
        order: 1,
      },
      {
        id: "tokyo",
        name: "東京",
        name_en: "Tokyo",
        postal_code: "150-0043",
        address_region: "東京都",
        address_locality: "渋谷区",
        street_address: "道玄坂1丁目10番8号 渋谷道玄坂東急ビル2F-C",
        address_en: "2F-C, Shibuya Dogenzaka Tokyu Bldg., 1-10-8 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan",
        is_headquarters: false,
        order: 2,
      },
    ],
  },
  areas,
  services,
  faqs,
  notices,
  categories: [
    { id: "cat-ai", slug: "ai", name_ja: "AI", name_en: "AI", description_ja: "AIと自動化に関する記事。", description_en: "Articles on AI and automation." },
    { id: "cat-creative", slug: "creative", name_ja: "creative", name_en: "creative", description_ja: "制作とデザインに関する記事。", description_en: "Articles on production and design." },
    { id: "cat-marketing", slug: "marketing", name_ja: "marketing", name_en: "marketing", description_ja: "マーケティングと検索に関する記事。", description_en: "Articles on marketing and search." },
    { id: "cat-tech", slug: "tech", name_ja: "tech", name_en: "tech", description_ja: "技術と業界の動きに関する記事。", description_en: "Articles on technology and the industry." },
  ],
  tags: [
    { id: "tag-ai", slug: "ai", name_ja: "AI", name_en: "AI" },
    { id: "tag-seo", slug: "seo", name_ja: "SEO", name_en: "SEO" },
    { id: "tag-wp", slug: "wordpress", name_ja: "WordPress", name_en: "WordPress" },
    { id: "tag-web", slug: "web", name_ja: "Web", name_en: "Web" },
  ],
  insights,
  pages,
  tools: [
    { group: "works", label_ja: "Ad", label_en: "Ad", items: "Google / Meta / TikTok / LINE" },
    { group: "works", label_ja: "Design", label_en: "Design", items: "Figma / Adobe" },
    { group: "works", label_ja: "AI Platforms", label_en: "AI Platforms", items: "Anthropic / xAI / OpenAI / Google" },
    { group: "works", label_ja: "Automation & Integration", label_en: "Automation & Integration", items: "Grok Bot / Claude Code / n8n / Make" },
    { group: "works", label_ja: "Development & Experience", label_en: "Development & Experience", items: "Astro / Headless CMS / Cloudflare / Hono" },
    { group: "works", label_ja: "Data & Optimization", label_en: "Data & Optimization", items: "Analytics / Search Console / Tag Manager" },
    { group: "prototypes", label_ja: "AI Exploration", label_en: "AI Exploration", items: "Runable / manus / Genspark" },
    { group: "prototypes", label_ja: "Video", label_en: "Video", items: "Higgsfield / Domo AI / KlingAI / Runway" },
    { group: "prototypes", label_ja: "Dev", label_en: "Dev", items: "Cursor / Xcode" },
    { group: "prototypes", label_ja: "3D", label_en: "3D", items: "Spline / Tripo Studio / Blender" },
    { group: "prototypes", label_ja: "Interaction & Motion", label_en: "Interaction & Motion", items: "Rive / Unicorn Studio / Lottie" },
  ],
};

export function noticeHasEnglish(notice: Notice): boolean {
  return Boolean(notice.title_en && notice.seo_en?.seo_description && notice.body_en?.length);
}
